export const DEMO = 'DEMO'

export const TOGGLE_SIDEBAR_VISIBLE = 'TOGGLE_SIDEBAR_VISIBLE'

export const SET_PAGE_INITED = 'SET_PAGE_INITED'

export const SET_PROGRESS_BAR_VISIBLE = 'SET_PROGRESS_BAR_VISIBLE'

export const UPDATE_PAGE_C = 'UPDATE_PAGE_C'

